version: "3.3"

services:
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
    restart: always
    ports:
      - 8090:80
#    logging:
#      driver: "fluentd"
#      options:
#        fluentd-address: localhost:24224
#        tag: docker.container_1
    depends_on:
      - "fluentd"
  fluentd:
    image: cheungpat/fluentd-s3
    restart: always
    environment:
      - 'FLUENTD_CONF=fluent.conf'
    volumes:
      - ./fluentd:/fluentd/etc
      - ./nginx/log:/var/log/nginx
    ports:
      - "24224:24224"
    logging:
      driver: "json-file"

